add_newline = false

format = """\
  $username\
  $hostname\
  $kubernetes\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $docker_context\
  $package\
  $elixir\
  $golang\
  $nodejs\
  $php\
  $python\
  $ruby\
  $rust\
  $terraform\
  $aws\
  $env_var\
  $crystal\
  $cmd_duration\
  $custom\
  $line_break\
  $memory_usage\
  $jobs\
  $time\
  $character"""
[character]
symbol = "➜"
error_symbol = "✗"
use_symbol_for_status = true


[time]
disabled = false
time_format = "[%d %b | %H:%M]"
utc_time_offset = "+5.5"

[jobs]
symbol = "+ "
threshold = 2

[memory_usage]
disabled = false

[cmd_duration]
min_time = 500
disabled = false
